// config.js
export const SUPABASE_URL = "https://amjvuowsufiecsaentdn.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtanZ1b3dzdWZpZWNzYWVudGRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwNjQyNTUsImV4cCI6MjA5NTY0MDI1NX0.3ZKvO9srohn18zM1jRaPsZt5u2Hcq84t8JyU5EJ8iGE";